prim_table = {
	'!': 'Police Stn',
	'"': 'No Symbol',
	'#': 'Digi',
	'$': 'Phone',
	'%': 'DX Cluster',
	'&': 'HF Gateway',
	"'": "Plane small",
	'(': 'Mob Sat Stn',
	')': 'Wheelchair',
	'*': 'Snowmobile',
	'+': 'Red Cross',
	',': 'Boy Scout',
	'-': 'Home',
	'.': 'X',
	'/': 'Red Dot',
	'0': 'Circle (0)',
	'1': 'Circle (1)',
	'2': 'Circle (2)',
	'3': 'Circle (3)',
	'4': 'Circle (4)',
	'5': 'Circle (5)',
	'6': 'Circle (6)',
	'7': 'Circle (7)',
	'8': 'Circle (8)',
	'9': 'Circle (9)',
	':': 'Fire',
	';': 'Campground',
	'<': 'Motorcycle',
	'?': 'File srv',
	'@': 'HC Future',
	'A': 'Aid Stn',
	'B': 'BBS',
	'C': 'Canoe',
	'D': 'No Symbol',
	'E': 'Eyeball',
	'F': 'Tractor',
	'G': 'Grid Squ.',
	'H': 'Hotel',
	'I': 'TCP/IP',
	'J': 'No Symbol',
	'K': 'School',
	'L': 'Usr Log-ON',
	'M': 'MacAPRS',
	'N': 'NTS Stn',
	'O': 'Balloon',
	'P': 'Police',
	'Q': 'TBD',
	'R': 'Rec Vehicle',
	'S': 'Shuttle',
	'T': 'SSTV',
	'U': 'Bus',
	'V': 'ATV',
	'W': 'WX Service',
	'X': 'Helo',
	'Y': 'Yacht',
	'Z': 'WinAPRS',
	'[': 'Jogger',
	'\\': 'Triangle',
	']': 'PBBS',
	'ˆ': 'Plane large',
	'_': 'WX Station',
	'`': 'Dish Antenna',
	'a': 'Ambulance',
	'b': 'Bike',
	'c': 'ICP',
	'd': 'Fire Station',
	'e': 'Horse',
	'f': 'Fire Truck',
	'g': 'Glider',
	'h': 'Hospital',
	'i': 'IOTA',
	'j': 'Jeep',
	'k': 'Truck',
	'l': 'Laptop',
	'm': 'Mic-E Repeater',
	'n': 'Node',
	'o': 'EOC',
	'p': 'Rover',
	'q': 'Grid Square',
	'r': 'Aerial',
	's': 'Power Boat',
	't': 'Truck Stop',
	'u': 'Truck 18wh.',
	'v': 'Van',
	'w': 'Water Station',
	'x': 'XAPRS',
	'y': 'Yagi',
	'z': 'Shelter',
	'{': 'No Symbol',
	'|': 'TNC Steam SW',
	'}': 'No Symbol',
	'-': 'TNC Stream SW'
}

alt_table = {
	'!': 'Emergency',
	'"': 'No Symbol',
	'#': 'No Digi',
	'$': 'Bank',
	'%': 'No Symbol',
	'&': 'No Diamond',
	"'": "Crash site",
	'(': 'Cloudy',
	')': 'MEO',
	'*': 'Snow',
	'+': 'Church',
	',': 'Girl Scout',
	'-': 'Home (HF)',
	'.': 'UnknownPos',
	'/': 'Desitnation',
	'0': 'No. Circle',
	'1': 'No Symbol',
	'2': 'No Symbol',
	'3': 'No Symbol',
	'4': 'No Symbol',
	'5': 'No Symbol',
	'6': 'No Symbol',
	'7': 'No Symbol',
	'8': 'No Symbol',
	'9': 'Petrol Stn',
	':': 'Hail',
	';': 'Park',
	'<': 'Gale Fl',
	'?': 'Info Kiosk',
	'@': 'Hurricane',
	'A': 'No. Box',
	'B': 'Snow blwng',
	'C': 'Coast Grd',
	'D': 'Drizzle',
	'E': 'Smoke',
	'F': 'Frze Rain',
	'G': 'Snow Shwr',
	'H': 'Haze',
	'I': 'Rain Shwr',
	'J': 'Lightning',
	'K': 'Kenwood',
	'L': 'Lighthouse',
	'M': 'No Symbol',
	'N': 'Nav Buoy',
	'O': 'Rocket',
	'P': 'Parking',
	'Q': 'Quake',
	'S': 'Sat/Pacsat',
	'T': 'Th-storm',
	'U': 'Sunny',
	'V': 'VORTAC',
	'W': 'No. WXS',
	'X': 'Pharmacy',
	'Y': 'No Symbol',
	'Z': 'No Symbol',
	'[': 'Wall Cloud',
	'\\': 'No Symbol',
	']': 'No Symbol',
	'ˆ': 'No. Plane',
	'_': 'No. WX Station',
	'`': 'Rain',
	'a': 'No. Diamond',
	'b': 'Dust blowing',
	'c': 'No. CivDef',
	'd': 'DX Spot',
	'e': 'Sleet',
	'f': 'Funnel Cloud',
	'g': 'Gale',
	'h': 'HAM Store',
	'i': 'No. Black Box',
	'j': 'Workzone',
	'k': 'SUV',
	'l': 'Area Locations',
	'm': 'Milepost',
	'n': 'No. Triangle',
	'o': 'Circle Small',
	'p': 'Part Clould',
	'q': 'No Symbol',
	'r': 'Restrooms',
	's': 'No. Boat',
	't': 'Tornado',
	'u': 'No. Truck',
	'v': 'No. Van',
	'w': 'Floolding',
	'x': 'No Symbol',
	'y': 'Sky Warning',
	'z': 'No. Shelter',
	'{': 'Fog',
	'|': 'TNC Stream',
	'}': 'No Symbol',
	'-': 'TNC Stream'
}
